version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/cv
    ports:
      - 1234:1234
    stdin_open: true
    tty: true
    command: ["npm", "run", "serve"]
