version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/cv/src
      - ./dist:/cv/dist
    ports:
      - 1234:1234
    stdin_open: true
    tty: true
